# Generated by Django 4.2.1 on 2023-12-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Категория')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_user', models.CharField(max_length=100, unique=True, verbose_name='Номер телефона')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('weight', models.CharField(blank=True, max_length=20, null='100г.', verbose_name='Вес')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/api/images/', verbose_name='Изображение товара')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Публикация')),
                ('cats', models.ManyToManyField(blank=True, related_name='posts', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-time_create',),
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usertelegram')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'ordering': ('id',),
            },
        ),
    ]
