# Generated by Django 4.2.1 on 2023-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('phone_user', models.CharField(max_length=100, verbose_name='Номер телефона')),
            ],
        ),
    ]
