# Generated by Django 4.2.1 on 2023-12-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id'),
        ),
    ]
