# Generated by Django 4.2.1 on 2023-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_usertelegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='phone_user',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
