# Generated by Django 4.2.1 on 2023-11-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_usertelegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertelegram',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
