# Generated by Django 4.2.1 on 2023-12-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_usertelegram_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
