# Generated by Django 4.2.1 on 2023-11-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_usertelegram_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='tags',
        ),
        migrations.AddField(
            model_name='catalog',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='cat', to='catalog.category', verbose_name='Категория'),
        ),
    ]
