# Generated by Django 4.2.1 on 2023-12-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.catalog',),
        ),
    ]
