# Generated by Django 4.2.1 on 2023-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_tag_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='phone_user',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер телефона'),
        ),
    ]
