# Generated by Django 4.2.1 on 2023-11-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_usertelegram_phone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
