# Generated by Django 4.2.1 on 2024-01-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_user'),
        ('catalog', '0005_productproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTelegram',
        ),
    ]
