# Generated by Django 4.2.1 on 2023-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_usertelegram_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='telegram_id',
            field=models.CharField(default=7404, max_length=100, unique=True, verbose_name='Телеграм ID'),
        ),
    ]
