# Generated by Django 4.2.1 on 2023-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_usertelegram_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null='100г.', verbose_name='Вес'),
            preserve_default='100г.',
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='telegram_id',
            field=models.CharField(default=2623, max_length=100, unique=True, verbose_name='Телеграм ID'),
        ),
    ]
