# Generated by Django 4.2.1 on 2023-12-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_catalog_options_alter_catalog_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='telegram_id',
            field=models.CharField(default=87562, max_length=100, unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usertelegram')),
            ],
        ),
    ]
