# Generated by Django 4.2.1 on 2023-12-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Имя пользователя')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('phone_user', models.CharField(max_length=100, null=True, unique=True, verbose_name='Номер телефона')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-id',),
            },
        ),
    ]
