# Generated by Django 4.2.1 on 2024-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_price', '0002_remove_discountprice_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountprice',
            name='price',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цена'),
        ),
    ]
